"""Initial migration

Revision ID: 6c9351d70967
Revises: 
Create Date: 2025-01-29 20:19:49.136712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c9351d70967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hanzi', sa.String(), nullable=False),
    sa.Column('pinyin', sa.String(), nullable=False),
    sa.Column('english_translation', sa.String(), nullable=False),
    sa.Column('hsk_level', sa.String(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_cards_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('learners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nickname', sa.String(), nullable=True),
    sa.Column('country_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], name=op.f('fk_learners_country_id_countries')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proficiencylevels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('learner_id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_proficiencylevels_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['learner_id'], ['learners.id'], name=op.f('fk_proficiencylevels_learner_id_learners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proficiencylevels')
    op.drop_table('learners')
    op.drop_table('cards')
    op.drop_table('countries')
    op.drop_table('categories')
    # ### end Alembic commands ###
