"""Adds relationships

Revision ID: d2bba56602ed
Revises: c8f32c3968e8
Create Date: 2025-01-28 08:23:16.693789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2bba56602ed'
down_revision = 'c8f32c3968e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_notes', sa.String(), nullable=True),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], name=op.f('fk_card_categories_card_id_cards'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_card_categories_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_categories')
    # ### end Alembic commands ###
